import torch
from torch import nn

class StateGenerator(nn.Module):
    """
    Generative next-token predictor to generate state transition distributions.

    Conditioned on policy and prior over states at start timestep (not necessarily current?).
    If we think of 'applying' a policy to a state, we would get another state. Thus, perhaps we 
    can think of the next sequence prediction here as 'given this sequence of previous states, and if I apply
    this policy to the latest state, what is the next possible state?'. The policy being applied in all
    previous states should already be encoded in their representation, since they were generated by the 
    same process.

    How can 'policy conditioning' be applied? Try concatenation first?

    Also, time steps are a bit of an arbitrage concept when it comes to what we are doing. For the sake of 
    simplicity for now, and so we can actually get things done, lets just assign how far we are looking forward and
    backward into a integer variable.

    TODO: What todo about covariance lol
    """

    def __init__(self):
        super().__init__()
        self.generative_model = something


    def forward(
        self,
        policy, 
        init_state_prior,
        prev_timesteps,
        future_timesteps,
    ):  
        start_state = init_state_prior(prev_timesteps)
        prev = torch.cat(policy, start_state)

        for i in range(prev_timesteps + future_timesteps):
            next = self.generative_model(prev)
            prev = prev.extend(next)  # or however we're merging tensors into a sequence

        return prev  # sequence of prev + future state distribution parameter vectors.
